### ISSUE TITLE
No first frame until resize

### ISSUE THREAD

**Issue by ccreeves** [Stanko/html-canvas-video-player#6]
First off, thanks for putting this together! I've almost got it working as needed.

The issue I'm having when implementing this in an iOS Cordova app is that the first frame is not drawn (correctly) until a `resize` event occurs. The canvas is simply black until I rotate the device at which point the first frame of the actual video is drawn.

Any idea why that may be?

**Comment by Stanko** [comment]
Thanks,
I'm using `canplaythrough` event on video to draw first frame on the initial load. Event is probably triggered before script managed to attach the event. Resize calls `drawFrame` again, that's why it works.

On the line `141` there is a code:

```
// Draws first frame
this.video.addEventListener('canplaythrough', cvpHandlers.videoCanPlayHandler = function() {
    self.drawFrame();
});
```

Try adding following fix after it

```
if (this.video.readyState >= 2) {
    self.drawFrame();
});
```

`readyState` prop gives back the information if the video is ready. Even if `canplaythrough` is already triggered, this should be able to draw the first frame. (Check `readyState` documentation on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState).)

Please test it, and if it helps, I'll add it to the code base.
Cheers!

**Comment by ccreeves** [comment]
Hi Stanko,

Appreciate the reply! I did check that `self.drawFrame();` was being called.

Turns out the problem was due to a mistake on my end. I'm displaying the video in a popup type element and I was initializing the `CanvasVideoPlayer` just before the parent div of the video related elements became visible. So `canplay` was firing before the video was actually visible. Oops.

Thanks!
Chris

**Comment by Stanko** [comment]
Nice, glad you got it. I'll add that check anyway, to have a safety net.
